name: lint

on:
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code 
        uses: actions/checkout@v3
      - name: check deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm 
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        run: npm i --force
      - name: Run ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: get repo code 
        uses: actions/checkout@v3
      - name: check deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm 
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        run: npm i --force
      - name: Build application
        run: npm run build
